### ISSUE TITLE
Project Checklist - Camping Idea

### ISSUE THREAD

**Issue by annarischitelli** [shadiaduery/bootcamp-group_project-3#1]
**Project Tasklist**
- [ ] Pull data files from Recreation.gov (create and account and download 
- [ ] Create SQL database and tables to hold data
- [ ] Import data to database 
- [ ] Clean data of any nulls
- [ ] Filter data to only include Oregon campgrounds
- [ ] Create a rolling average (?) for temperature
- [ ] Average temperature by month (?)
- [ ] Create HTML page @annarischitelli 
- [ ] Create a section of HTML page that will scrape/ pull in latest camping news or something related @annarischitelli 
- [ ] Visualization 1 - Map of state with campgrounds + info of weather (+layers: grocery stores, gas stations, etc.)
- [ ] Visualization 2 - 
- [ ] Visualization 3 - 

Data from Recreation.gov
- "FacilityID" = primary key in database 
- "Park" = Facility Name
- "RegionDescription" = Region of campground
- "FacilityLongitude" = Longitude
- "FacilityLatitude" = Latitude
- "SiteType" = 
- Number of sites per campground
- 

Weather data
- Average high
- Average low
- Average precipitation

Web Scraping
- Camping news

Create 7 polygons (regions from Travel Oregon)
- 5 years of weather data in Oregon
- Add avg high/low temp per region
- Add avg precip per region
- Each day will have all of the data

Input of user will be date - show user 7 regions (number for date), select campground, and see in that region, what campgrounds exist there
