### ISSUE TITLE
Project Checklist - Commuting, Emissions, etc.

### ISSUE THREAD

**Issue by annarischitelli** [shadiaduery/bootcamp-group_project-3#2]
Dates: 2009 - 2019 (10 years)
*Compare two metro areas: Portland & Seattle

**Question:** 
Does an increase bicycling does it impact transportation emissions?

**Data sets:**
Transportation emissions data 
Commute data (strava)

**Background research:**
- [ ] Research each cities initiatives (if any) exists to encourage cycling?

**To-Do before Monday**
- [ ] Submit link of existing repo @shadiaduery 
- [ ] Update Readme with new project info @annarischitelli 
- [ ] Get strava data @annarischitelli 
- [ ] Get transportation emissions data @newbeadwork 
- [ ] Lit review about city initiatives @shadiaduery 
- [ ] Data on bike roads @larunachalam10 
- [ ] Population census data from Seattle area and Portland metro to compare growth for timeframe @vinnie3030 

**To-Do on Monday**
- [ ] Database mapping and connecting our new information
- [ ] Clean data as a group
- [ ] Preliminary analysis
- [ ] Determine what type of visualizations

**Requirements**
- JSON: strava data
- API: census data
- Save everything in database: create SQL database
- Create D3 chart @newbeadwork 
- Create HTML page @annarischitelli 
- 100 records - yep
- Interactive visualizations: dropdown on activity type?
